{$include_once Types/Type_TBox.pas}
{$include_once Types/Type_TPoint.pas}
{$include_once Types/Type_String.pas}
{$include_once Types/Type_TPointArray.pas}
{$include_once Types/Type_TByteArray.pas}
{$include_once Types/Type_TIntArray.pas}
{$include_once Types/Type_TFloatArray.pas}
{$include_once Types/Type_TDoubleArray.pas}
{$include_once Types/Type_TExtArray.pas}
{$include_once Types/Type_TBoxArray.pas}
{$include_once Types/Type_TStringArray.pas}
{$include_once Types/Type_T2DPointArray.pas}
{$include_once Types/Type_T2DByteArray.pas}
{$include_once Types/Type_T2DIntArray.pas}
{$include_once Types/Type_T2DExtArray.pas}